sudo_pass: "{{ lookup('hashi_vault', 'secret=secrets/data/sudo-access').password }}"
mysql_username: "ecomuser"
mysql_password: "{{ lookup('hashi_vault', 'secret=secrets/data/db-secrets').password }}"
mysql_db: "ecomdb"
